CREATE TABLE [dbo].[Quote] (
    [QuoteID]                VARCHAR (50)   NOT NULL,
    [ModifiedDate]           DATETIME2 (7)  NULL,
    [CreationDate]           DATETIME2 (7)  NULL,
    [ApprovalDate]           DATETIME2 (7)  NULL,
    [WorkflowStatus]         VARCHAR (50)   NULL,
    [CRMQuoteNumber]         VARCHAR (50)   NULL,
    [SalesType]              VARCHAR (50)   NULL,
    [CustomerReference]      NVARCHAR(MAX)  NULL,
    [PartnerName]            NVARCHAR(MAX)  NULL,
    [PartnerDivision]        NVARCHAR(MAX)  NULL,
    [AccountContact]         NVARCHAR(MAX)  NULL,
    [OpportunityName]        NVARCHAR(MAX)  NULL,
    [CompetitionConcern1]    VARCHAR (MAX)  NULL,
    [CompetitionConcern2]    VARCHAR (MAX)  NULL,
    [CompetitionConcern3]    VARCHAR (MAX)  NULL,
    [CompetitionReason1]     NVARCHAR(MAX)  NULL,
    [CompetitionReason2]     NVARCHAR(MAX)  NULL,
    [CompetitionReason3]     NVARCHAR(MAX)  NULL,
    [Region]                 VARCHAR (50)   NULL,
    [Currency]               VARCHAR (50)   NULL,
    [ExchangeRate]           NUMERIC (5, 2) NULL,
    [ExchangeRateDate]       NUMERIC (18)   NULL,
    [TotalBidGoalSeekAmount] SMALLMONEY     NULL,
    [SupportSLADiscount]     NUMERIC (5, 2) NULL,
    PRIMARY KEY CLUSTERED ([QuoteID] ASC)
)
