CREATE TABLE [dbo].[QuoteDetail]
(
	[QuoteDetaiIID] INT IDENTITY not null PRIMARY KEY, 
    [QuoteID] VARCHAR(50) NOT NULL, 
    [ModifiedDate] DATETIME2 NULL, 
    [ManufacturerName] NVARCHAR(MAX) NULL, 
    [PartNumber] NVARCHAR(MAX) NULL, 
    [ProductName] NVARCHAR(MAX) NULL, 
    [ModelNumber] NVARCHAR(MAX) NULL, 
    [SerialNumber] NVARCHAR(MAX) NULL, 
    [ConfigurationNeeded] BIT NULL, 
    [MaxAssumption] VARCHAR(50) NULL, 
    [MedAssumption] VARCHAR(50) NULL, 
    [MinAssumption] VARCHAR(50) NULL, 
    [AssumedSpec] NVARCHAR(MAX) NULL, 
    [ConfigurationNotes] NVARCHAR(MAX) NULL, 
    [ConfigurationLevel] VARCHAR(50) NULL, 
    [LocationRegion] VARCHAR(50) NULL, 
    [LocationAddress] NVARCHAR(MAX) NULL, 
    [LocationStateProvince] NVARCHAR(MAX) NULL, 
    [LocationCity] NVARCHAR(MAX) NULL, 
    [LocationCountry] NVARCHAR(MAX) NULL, 
    [LocationSupported] VARCHAR(50) NULL, 
    [LocationPostCode] VARCHAR(50) NULL, 
    [SupportLevel] VARCHAR(50) NULL, 
    [CoverageSLA] VARCHAR(50) NULL, 
    [Qty] NUMERIC NULL, 
    [CoverageStartDate] DATE NULL, 
    [CoverageEndDate] DATE NULL, 
    [Months] NUMERIC(3) NULL, 
    [MonthsCalculated] NUMERIC(3) NULL, 
    [PricingSource] VARCHAR(50) NULL, 
    [sniFlags] VARCHAR(50) NULL, 
    [PriceMMC] NUMERIC(12) NULL, 
    [Software] NUMERIC(12) NULL, 
    [SalesDiscount] NUMERIC(12) NULL, 
    [SalesDiscountTotal] SMALLMONEY NULL, 
    [ListMMCTotal] NUMERIC(12) NULL, 
    [Bid] SMALLMONEY NULL, 
    [FlagDAM] VARCHAR(MAX) NULL, 
    [BidOverall] NUMERIC(12) NULL, 
    [FlagDAMOverall] NUMERIC(12) NULL, 
    [CounteredPriceApproval] NUMERIC(12) NULL 
)
